version: '2'
services:
  gogs:
    image: gogs/gogs:latest
    volumes:
      - /tmp/gogs-data:/data
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
  postgres:
    image: postgres:alpine
    volumes:
      - /tmp/gogs-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=gogs
  jenkins:
    build:
      context: .
      dockerfile: ../jenkins-Dockerfile/Dockerfile
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home  
    image: jenkins/jenkins
 