version: '2'
services:
  app:
    image: gogs/gogs:latest
    volumes:
      - /tmp/gogs-data:/data
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
  postgres:
    image: postgres:alpine
    volumes:
      - /tmp/gogs-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=gogs
  jenkins:
    build:
      context: .
      dockerfile: ../jenkins-Dockerfile/Dockerfile
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home  
    image: jenkins/jenkins
  adminPortal:
    build:
      context: .
      dockerfile: ../test-C-Admin-Portal/Dockerfile
    ports:
      - "50001:50001"
      - "4200:4200" 
    image: adminportal  
  studentenPortal:
    build:
      context: .
      dockerfile: ../test-C-Studenten-Portal/Dockerfile
    ports:
      - "50003:50003"
      - "8886:8886" 
    image: studentenporstltest  
  backendtestc:
    build:
      context: .
      dockerfile: ../backend-Test-C/Dockerfile
    ports:
      - "50004:50004"
      - "8088:8088" 
    image: backend-test-c     